# a cluster with 3 control-plane nodes and 3 workers
#kind create cluster --name k8s-playground --config kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker