apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual
spec:
  nodeName: k8s-playground-worker # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent